apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: fakedings
  namespace: token
  labels:
    team: token
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /internal/isalive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isalive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 10m
      memory: 128Mi
  ingresses:
    - https://fakedings.intern.dev.nav.no
